---
abstract: "A simple parser for Makefiles\r"
author: "Agent Zhang, <agentzh@gmail.com>\r"
build_requires:
  Test::More: 0.66
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Makefile-Parser
no_index:
  directory:
    - inc
    - t
requires:
  Cwd: 0
  File::Spec: 0
  List::MoreUtils: 0
  Text::Balanced: 0
  perl: 5.6.1
version: 0.15
