abstract: "A Simple Parser for Makefiles\r"
author: "Agent Zhang, <agent2002@126.com>\r"
build_requires:
  Test::More: 0.66
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Makefile-Parser
no_index:
  directory:
    - inc
    - t
requires:
  List::MoreUtils: 0
  Text::Balanced: 0
  perl: 5.6.1
version: 0.12
